
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

const MODEL_NAME = 'gemini-2.5-flash-image';

export class GeminiService {
  private static ai: GoogleGenAI;

  private static getClient() {
    if (!this.ai) {
      this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });
    }
    return this.ai;
  }

  /**
   * Processes an image based on a text prompt using gemini-2.5-flash-image.
   * @param base64Image The image in base64 format (data:image/png;base64,...)
   * @param prompt The editing instruction.
   */
  static async editImage(base64Image: string, prompt: string): Promise<string> {
    const ai = this.getClient();
    
    // Extract base64 data and mime type
    const [header, data] = base64Image.split(',');
    const mimeType = header.match(/:(.*?);/)?.[1] || 'image/png';

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              data: data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    if (!response.candidates?.[0]?.content?.parts) {
      throw new Error("No output generated by AI.");
    }

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("The AI returned a text response instead of an image. Try a more specific prompt.");
  }

  /**
   * Specialized method to transform a person into a female version.
   */
  static async generateFemaleVersion(base64Image: string): Promise<string> {
    const prompt = `Transform the ENTIRE PERSON in this photo into a realistic female version of themselves. 

    CRITICAL INSTRUCTION 1 - FULL BODY & HANDS (MANDATORY): You MUST completely transform the entire body, not just the face. 
    - The body MUST have female anatomy: narrower shoulders, feminine neck, and natural female breast/chest.
    - The limbs and hands MUST be completely changed to be soft, slender, delicate, and distinctly feminine. You MUST NOT leave masculine hands, arms, or shoulders in the image. If hands are visible, they MUST be made feminine.
    - Adjust the clothing fit if necessary to match the new female body shape.
    
    CRITICAL INSTRUCTION 2 - FACIAL IDENTITY, AGE & HAIR: While the body must change completely to female, the FACE must retain the original person's core identity, but with strict female traits.
    - REMOVE ALL FACIAL HAIR (CRITICAL): You MUST completely remove any mustache, beard, goatee, or stubble. The face must be completely smooth and hairless.
    - Preserve the underlying facial bone structure, eye shape, skin texture, ethnicity, and EXACT AGE. 
    - Do not make them look younger, older, or like a fake airbrushed model.
    - Soften the jawline and add natural feminine head hair, but they must still be instantly recognizable as the same person.
    
    The final image must be highly realistic, matching the original lighting and environment perfectly.`;
    
    return this.editImage(base64Image, prompt);
  }

  /**
   * Specialized method to transform a person into a male version.
   */
  static async generateMaleVersion(base64Image: string): Promise<string> {
    const prompt = `Transform the ENTIRE PERSON in this photo into a realistic male version of themselves. 

    CRITICAL INSTRUCTION 1 - FULL BODY & HANDS (MANDATORY): You MUST completely transform the entire body, not just the face. 
    - The body MUST have male anatomy: broader shoulders, thicker neck, and a flat male chest.
    - The limbs and hands MUST be completely changed to be masculine, thicker, and distinctly male. You MUST NOT leave feminine hands, arms, or shoulders in the image. If hands are visible, they MUST be made masculine.
    - Adjust the clothing fit if necessary to match the new male body shape.
    
    CRITICAL INSTRUCTION 2 - FACIAL IDENTITY, AGE & HAIR: While the body must change completely to male, the FACE must retain the original person's core identity, but with strict male traits.
    - Add masculine facial features: sharper, more angular jawline, thicker eyebrows. You may add natural, subtle facial hair (like light stubble) if it fits the age.
    - Preserve the underlying facial bone structure, eye shape, skin texture, ethnicity, and EXACT AGE. 
    - Do not make them look younger, older, or like a fake airbrushed model.
    - Give them a natural masculine haircut, but they must still be instantly recognizable as the same person.
    
    The final image must be highly realistic, matching the original lighting and environment perfectly.`;
    
    return this.editImage(base64Image, prompt);
  }
}
